fix: bad disposition on gallery.html & small tweak from the issue #38
Simplon-hdf/Brief_photographe_NewDoctors pull request #43
Opened 2024-05-05 15:58 UTC by RenaudBaussart

2024-05-05 19:22 UTC, Hugo-walando requested changes
Fix conflicts

2024-05-05 19:22 UTC, Achap05 requested changes
- unresolved conflicts
- pr name

2024-05-06 07:07 UTC, RenaudBaussart commented
conflict fix

2024-05-06 07:15 UTC, Achap05 approved these changes

2024-05-06 07:16 UTC, Hugo-walando approved these changes

2024-05-06 07:16 UTC, merged